volumes:
  database_data:
  redis_data:

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - database
      - redis

  celery:
    build: .
    command: celery -A config.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - database
      - redis

  database:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
