volumes:
  database_data_dev:
  redis_data_dev:

services:
  front-dev:
    build:
      context: ./front
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - /app/node_modules

  api-dev:
    build:
      context: .
      target: development
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - database-dev
      - redis-dev

  celery-dev:
    build:
      context: .
      target: celery
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - database-dev
      - redis-dev

  database-dev:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - database_data_dev:/var/lib/postgresql/data

  redis-dev:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
