# Generated by Django 5.2 on 2025-04-18 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_members",
                through="core.RoomMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="roommember",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.room",
            ),
        ),
        migrations.AlterField(
            model_name="roommember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
